### ISSUE TITLE
The type of instance variables is not automatically determined from the constructor

### ISSUE THREAD

**Issue by Tazdraperm** [YellowAfterlife/GMEdit#120]
Steps to reproduce:
1. Create a script with a constructor function
![hMZQwWF3twU](https://user-images.githubusercontent.com/27915583/108769113-99f63f00-7569-11eb-8b6d-1d1d24f5fa91.jpg)

2. Initialize an instance variable using the new keyword and function above
![vIfNPgKGmEA](https://user-images.githubusercontent.com/27915583/108769114-9a8ed580-7569-11eb-882f-f2f1242680bc.jpg)

3. Auto completion does not pop up.

No autocompletion pops up.

**Comment by Tazdraperm** [comment]
The same appears to happen for primitive types, e.g. variable = 5 or variable = "str".

**Comment by AntonBergaker** [comment]
Only local variables can figure out their type based on what's assigned to them at the moment. For any other type of variable you need to use ///@is {type} to get the autocomplete unfortunately.

**Comment by YellowAfterlife** [comment]
What Anton said - I can add a separate setting for extremely obvious cases like `v = <digit>`, `v = "`, and `v = new <name>` (which will fail if <name> is a macro, btw) very specifically, but anything smarter than that requires a complete rewrite of how project indexing works (and to do it in multiple passes), which is a whole lot of work.

**Comment by Tazdraperm** [comment]
That would be a really good feature. Mostly the `v = new <name>`  case, since it allows you to use auto-complete on instance variables.
