### ISSUE TITLE
Warning when trying to access built-in variables from outside an object

### ISSUE THREAD

**Issue by massim0g** [YellowAfterlife/GMEdit#121]
![image](https://user-images.githubusercontent.com/8515882/108773539-811b6880-752c-11eb-937e-ae21de22bf1e.png)
![image](https://user-images.githubusercontent.com/8515882/108775181-ba54d800-752e-11eb-845c-1318a0cef822.png)

Seems to happen everywhere.

**Comment by YellowAfterlife** [comment]
Most likely fixed in the new beta, but please reopen with reproduction steps if it isn't.
