### ISSUE TITLE
Visual cursor misaligned with actual insert position when using different font (size?)s

### ISSUE THREAD

**Issue by zulc22** [YellowAfterlife/GMEdit#122]
I don't know what the "intended" method is for changing the font-- I've seen screenshots of this program using fonts other than the default, but no themes I downloaded even had the string `font` in them.

I created a theme that just contains `#main .gml * { font-family: 'PxPlus IBM BIOS-2y'; font-size: 16px; }`, and when I do that, the cursor is completely misaligned.

![image](https://user-images.githubusercontent.com/54846511/108799009-0fe7af80-7544-11eb-832d-9c0989d30257.png)

![image](https://user-images.githubusercontent.com/54846511/108799072-41f91180-7544-11eb-9f08-e58e0c8b0068.png)

**Comment by zulc22** [comment]
![image](https://user-images.githubusercontent.com/54846511/108799864-53431d80-7546-11eb-8255-aafe8cf55f9a.png)

**Comment by YellowAfterlife** [comment]
The intended way of changing the font is going into code editor settings (Preferences ➜ Code Editor ➜ Code Editor Settings or press `Ctrl+,`) and setting it there.

If you absolutely need to change the font in your theme, use `.ace-tm` for selector so that you cover both the actual code and the guideline layer where the cursor resides.

**Comment by zulc22** [comment]
thank you, that's really hard to find. the settings need work

**Comment by YellowAfterlife** [comment]
Should the "code editor settings" button be bigger/shinier? If I merge them into the menu, you would not be able to find _anything else_ due to how many there are in that submenu.

**Comment by YellowAfterlife** [comment]
Moved both Code Editor section and the Code Editor Settings button a little up in the preferences (as these would probably be the ones to be accessed most often), made the buttons larger, and added a clarification text next to the first one for anyone quickly looking through them - will be in the next beta.
![image](https://user-images.githubusercontent.com/731492/109026026-f4a5ad00-76c7-11eb-8efc-06319f1b1090.png)
