### ISSUE TITLE
Warning line highlighting not moving when adding/removing code lines

### ISSUE THREAD

**Issue by Tazdraperm** [YellowAfterlife/GMEdit#124]
![ErrorHighlightingBug](https://user-images.githubusercontent.com/27915583/109177455-df4c8380-7798-11eb-8ccf-6bbc2a333413.gif)

Steps to reproduce:
1. Write any code that produces a warning
2. Add/remove lines before the line with the warning

Ctrl+S fixes everything.
Also, I'm using the latest GMEdit version available on GitHub if it's important.

**Comment by YellowAfterlife** [comment]
I am aware of this but it is unclear as to how make markers that will follow along with edits in Ace.js - at most I can just clear the warning markers as soon as line count for the file changes.

**Comment by Tazdraperm** [comment]
Well, if it cannot be easily fixed, it's not a big deal then, since you can just do Ctrl+S any time. 
Clearing warnings might be a good solution though.
