### ISSUE TITLE
Implicit instance variable typing not working for built-in functions

### ISSUE THREAD

**Issue by Tazdraperm** [YellowAfterlife/GMEdit#125]
I've tried the latest GMEdit version from GitHub. Implicit instance variables typing works really well and does a great job for auto-completion. However, it does not work when it comes to the built-in functions. For example:
![image](https://user-images.githubusercontent.com/27915583/109180268-be396200-779b-11eb-9fd4-c6358a1738e8.png)

Warnings expected to appear on lines 19 and 22 here.

This is more like a feature request rather than a bug. But since typing works well for constructors and types for all built-in functions are known, I assume it shouldn't be hard to implement such a feature (at least I hope so).

UPD: The same appears to happen for assets:
![image](https://user-images.githubusercontent.com/27915583/109183809-63096e80-779f-11eb-86d8-43c2c646e6b8.png)

**Comment by AntonBergaker** [comment]
I'm massively in favor of this suggestion. The only potential issue is that it'd then be inconsistent behavior between user scripts and built in functions. (which can be fixed by also allowing it for user scripts if they're explicitly typed 😏)

**Comment by Tazdraperm** [comment]
This would be a great step towards typed GML!

**Comment by Tazdraperm** [comment]
Ideally, it should behave the same as "var" in C#, determining variable types automatically wherever it's possible. But I understand that there might be a lot of complicated cases.

**Comment by AntonBergaker** [comment]
This is epic.

**Comment by YellowAfterlife** [comment]
Note that while this will work for something like `buffer_create`, `instance_create[_depth]` or `array_create` will not parse the arguments to derive types.

**Comment by Tazdraperm** [comment]
Thanks for the update! This is a really cool feature!
Just wondering, why doesn't it work the same as for local variables? Is there any major difference in how local/instance variables are processed?
![image](https://user-images.githubusercontent.com/27915583/109223910-4f283180-77cc-11eb-89fd-f77d92ca3887.png)

**Comment by YellowAfterlife** [comment]
The two are very different:

- Indexer ([parsers.GmlSeeker](https://github.com/YellowAfterlife/GMEdit/blob/master/src/parsers/GmlSeeker.hx)) is lightweight and has no knowledge about project structure. It is fully prepared for half of the code being garbage (e.g. because you are using macros that have not been indexed yet).
- Linter ([parsers.linter.GmlLinter](https://github.com/YellowAfterlife/GMEdit/blob/master/src/parsers/linter/GmlLinter.hx)) is aware of the syntax, can process multi-level macros, and requires the project structure (macros, script/variable types, globalvars, etc.) to be as known as it can be.

As I have mentioned in #120, it is not impossible to rewrite the two to utilize the linter in indexing phase, but this requires at least two indexing passes - first to pick up declarations (macros, globalvars, script/function names and JSDoc), then to use linter to resolve hopefully-more-typed variable assignments. If any of these depends on other variables, additional passes are required and side effects are a granted. All in all, no less than a few decades of work total.

**Comment by Tazdraperm** [comment]
I have two more questions/suggestions related to typing:
1. Is determining instance variables types from user-defined functions with known return type (either with `@returns` or `function()->T`) as complicated as in the situation we discussed above? It would be a really great feature. Here's a small example:
![image](https://user-images.githubusercontent.com/27915583/109314679-b55b9580-785a-11eb-9829-4223b48f2859.png)
![image](https://user-images.githubusercontent.com/27915583/109314691-bab8e000-785a-11eb-9cf4-5a8f6d3559aa.png)
It seems like GMEdit knows what type `num.increment()` is but ignores it when determining `num_inc` type, so it's *probably* could be fixed easily.

2. This one is more like a question. I have the following code in the Create event:
![image](https://user-images.githubusercontent.com/27915583/109315498-a88b7180-785b-11eb-95d1-d768bd780513.png)

It's obviously impossible for GMEdit to know that `-1` is a surface. It could be compared with `var obj = null` in C#, which is not allowed. So I tried to declare types explicitly using `@is {surface}`. However, it led me to the warning:
![image](https://user-images.githubusercontent.com/27915583/109315854-09b34500-785c-11eb-8000-a81ac78ea3e2.png)
This is also understandable since `-1` is a `number`, not a `surface`. Then I've tried to use  `@is {surface|number}. This removed the warning, but led to the new one:
![image](https://user-images.githubusercontent.com/27915583/109316341-9100b880-785c-11eb-9ca8-700fa305fc66.png)

So, the question is, what types should be used here to avoid warnings?

**Comment by YellowAfterlife** [comment]
> It seems like GMEdit knows what type num.increment() is but ignores it when determining num_inc type, so it's probably could be fixed easily.

GMEdit knows what num.increment is _at linter phase_, but there is no guarantee that `Num` script will be indexed before the object/script using it will be, and there is no way to tell where definition of `Num` is with 2.3 script changes. In fact, you could have
```js
function Some() constructor {
    a = new Num();
    b = a.increment();
}
function Num() {
    // ...
}
```
and that would be valid code that compiles, but absolutely could not be resolved in a single pass.

> It's obviously impossible for GMEdit to know that -1 is a surface. It could be compared with var obj = null in C#, which is not allowed. So I tried to declare types explicitly using `@is` {surface}. However, it led me to the warning:

An equivalent to C# `null` in GML would be `undefined`, which I suggest to use in anticipation of data types eventually becoming references rather that indexes. If you absolutely require numeric comparisons, use `noone`, which is allowed to cast to any type.

**Comment by Tazdraperm** [comment]
1. Well, that's pretty much clear
2. Using `undefined` was my very first suggestions, however, it failed for two reasons:
a. Still gives a warning.
![image](https://user-images.githubusercontent.com/27915583/109320784-77ae3b00-7861-11eb-9905-a07470fbed30.png)
b. The warning can be eliminated using `cast undefined`. But unfortunately, GMS does not allow to pass `undefined` into functions like `surface_exists`. That's a bit counterintuitive for me, but we have what we have.

Using `noone` works just fine without casting or anything else, so it's probably the best solution. Thank you!
