### ISSUE TITLE
Cannot change local variable type once defined it

### ISSUE THREAD

**Issue by Tazdraperm** [YellowAfterlife/GMEdit#126]
The gif demonstrating the issue:
![LocalVariableTypingBug2](https://user-images.githubusercontent.com/27915583/109186266-cdbba980-77a1-11eb-8a0a-b74f6c742021.gif)

This only happens for local variables, everything works just fine for instance variables.
Also, restarting the GMEdit resolves this issue.

**Comment by YellowAfterlife** [comment]
I'll need better reproduction steps (such as settings used and where you are writing the code) for this.

**Comment by Tazdraperm** [comment]
So, I've tried to simplify this case and this is what I've got so far:
![LocalVariableTypingBug001](https://user-images.githubusercontent.com/27915583/109219483-bba13180-77c8-11eb-864a-578d93ea2549.gif)

Steps to reproduce:
1. Create an empty GMS2 project. I'm using the latest stable IDE/runtime.
2. Open this project in GMEdit. I'm using the latest GMEdit Beta version for Windows from itch.io. All GMEdit files in AppData/Roaming erased, no external plugins installed. No setting changed except this one:
![image](https://user-images.githubusercontent.com/27915583/109219966-5dc11980-77c9-11eb-865d-eb5aeabd8a78.png)
3. Create a new object
4. Define create event
5. Define local variable of any type
6. Hit Ctrl+S
7. Change previously created variable's type
8. Hit Ctrl+S again
9. The warning appears: "Implicit redefinition of type for local variable %name% from %old_type% to %new_type%

The only way to resolve this is to restart GMEdit.

**Comment by YellowAfterlife** [comment]
Also,

> The only way to resolve this is to restart GMEdit.

Saving for very rare cases, there is no need to restart GMEdit to clean out project state - you can press Ctrl+R to reload the project.

**Comment by Tazdraperm** [comment]
> Also,
> 
> > The only way to resolve this is to restart GMEdit.
> 
> Saving for very rare cases, there is no need to restart GMEdit to clean out project state - you can press Ctrl+R to reload the project.

Thanks for the fix!
I'm aware of Ctr+R, but it did not help here. Only restarting GMEdit (either manually or via Preferences-> Reload GMEdit) worked out for me for some reason.
