### ISSUE TITLE
Instance variables that falls under "private variables regex" completely ignored by GMEdit

### ISSUE THREAD

**Issue by Tazdraperm** [YellowAfterlife/GMEdit#128]
Example regex:
![image](https://user-images.githubusercontent.com/27915583/109333547-a41d8380-7870-11eb-8460-43b3dad1fc1d.png)

It results in the following:
![image](https://user-images.githubusercontent.com/27915583/109333881-0aa2a180-7871-11eb-8778-5fa36e1d9b79.png)
![image](https://user-images.githubusercontent.com/27915583/109333899-0e362880-7871-11eb-828a-2ebe4958f400.png)

Variable is not recognized as a part of the struct at all, thus no type checks.

Also, resetting regex back to an empty string in `Project properties` does not actually reset it.  I've only managed to reset it manually via `properties.json`.

**Comment by YellowAfterlife** [comment]
A good example of how agreeing to add literally anything - no matter how small of a feature - will inevitably cost you maintenance time at some point in future.

**Comment by Tazdraperm** [comment]
Yes, but I find this particular addition very useful. Thanks for the fix!
