### ISSUE TITLE
Can't update YY: unexpected -

### ISSUE THREAD

**Issue by Xiraiden** [YellowAfterlife/GMEdit#150]
![image](https://user-images.githubusercontent.com/31773946/120257105-35780980-c255-11eb-8176-fdcf4c88c464.png)

**Comment by YellowAfterlife** [comment]
What did your Variable Definitions look like?

**Comment by Xiraiden** [comment]
![image](https://user-images.githubusercontent.com/31773946/120298503-c23fb900-c28f-11eb-82af-77e5f6f80954.png)

**Comment by YellowAfterlife** [comment]
Well

Why are you storing an array in a variable that you have indicated to be a Real?

Somewhat surprising that GMS2 didn't complain about it

**Comment by Xiraiden** [comment]
if i am being honest i have no idea exactly as i am learning as im going and following a course. he said the we are doing it this way as we might have various arguments to pass through and it avoids making a bunch of individual variables.

**Comment by YellowAfterlife** [comment]
If the variable stores an array, the value type should be "Expression", not "Real".

Seeing that GMS2 IDE doesn't complain about this (so far?), I'll look into supporting mismatched values for Real-typed variables in future.

**Comment by Xiraiden** [comment]
thank you.
