### ISSUE TITLE
Feature request - open rooms and tilesets in the software “Tiled”

### ISSUE THREAD

**Issue by FireSquid6** [YellowAfterlife/GMEdit#151]
I'm not sure how hard this would be, but since Tiled can export to gm room files it might be cool to be able to open a room in it or create a tileset in it since it has a better autotiling system.

**Comment by YellowAfterlife** [comment]
Tiled can _export_ GM rooms, but it cannot _import_ them, so you can't really "open a room in it".

You can place your TMX files in your Included Files (having disabled them for export) or use [Raw Directories](https://github.com/YAL-GMEdit/raw-directories) plugin to easily access related files from GMEdit.
