### ISSUE TITLE
Documentation Imporovement - Add more GIFs to docs.

### ISSUE THREAD

**Issue by iiviigames** [YellowAfterlife/GMEdit#153]
Specifically [this page](https://github.com/YellowAfterlife/GMEdit/wiki/Using-@hint-comments). 

If help is needed, I can do this when I have free time. Having gifs makes the process of troubleshooting infinitely more simple.
I love writing docs too. So, if it's not done by the time I try this out, I will send mine over!

**Comment by YellowAfterlife** [comment]
I'm not entirely sure how GIFs would help with this specific page (given that it's an in-depth explanation with subsequent examples), but I'm open to ideas

**Comment by iiviigames** [comment]
I am a fool. Sorry. Love.
