### ISSUE TITLE
GMEdit thinks "camera" is a built-in namespace

### ISSUE THREAD

**Issue by MangoDev1** [YellowAfterlife/GMEdit#156]
When I try to create a variable named `camera` in GMEdit, it thinks it is a built-in namespace. The weird thing is that in GMS2, `camera` is just flagged as another user-created variable. I have no custom dialects or code snippets or anything like that. Also, when I turn off the setting to allow `#import` in GMEdit, it doesn't stop the `camera` variable being called a namespace by the program.
It doesn't affect the game, it's just odd behavior and somewhat inconvenient, so I hope it's alright if I put this here.

Here's a screenshot of what I'm talking about:
![image](https://user-images.githubusercontent.com/94928669/143672356-3b783797-8aa9-4326-93dc-ea5bf99852b6.png)

The version of GMEdit I'm using is the (as of writing) most recent Windows beta on the itch.io page. I'm also using GMS2.3.
How to reproduce: type in `camera` and look in the autocomplete popup.

**Comment by YellowAfterlife** [comment]
This is a limitation of the current syntax highlighting - it is not context-aware, so it does not know whether the word `camera` is inside a type specification or not. At most I can block it from coloring unless preceded by a `:`, but this would backfire on ternary operators and `case:`, along with _not_ highlighting for things like `var map:ds_map<string, camera>`
