### ISSUE TITLE
Combined View breaks function/asset highlighting

### ISSUE THREAD

**Issue by Oracizan** [YellowAfterlife/GMEdit#158]
![image](https://user-images.githubusercontent.com/13291177/146667792-96f8665c-0db2-49ea-9426-4f80fc1490a1.png)

I'm unsure why, but it seems like opening a folder in Combined View breaks function/asset highlighting (even if the folder only contains one script).

To reproduce:

1. Open a script in regular view and note that functions are highlighted correctly.
2. Close the script. 
3. Open a combined view containing the script. Note that functions are not highlighted.
4. Close the combined view.
5. Open the script in regular view again. Note that functions are not highlighted.
6. Save the script. Note that the functions are highlighted correctly.

**Comment by YellowAfterlife** [comment]
Combined View is kind of strange with 2.3, but I cannot seem to reproduce this specific issue - may need a more specific sample

**Comment by Oracizan** [comment]
Here is a minimal sample project that I can reproduce the issue with (no plugins, default theme, beta GMEdit compiled at Dec 8, 2021).

https://www.dropbox.com/s/ruo2g4qs3jw11qx/CombinedTest.zip?dl=1

**Comment by Oracizan** [comment]
Thanks! Works now.
