### ISSUE TITLE
Issues when editing Snippets

### ISSUE THREAD

**Issue by brady-goldsworthy** [YellowAfterlife/GMEdit#163]
When trying to edit the gml.snippets file, I'm seeing unexpected behavior.

Contents of updated gml.snippets:

```
snippet switch
    switch ${1:var} {
        case ${2:1}:
            
        break;
        case ${3:2}:
            
        break;
        default:
            throw_error("Error! Reached default in switch statement");
    }
    
    
snippet for
    ${1:_len} = array_length(_arr);
	for (${2:_i} = ${3:0}; ${4:$2 < _len}; $2${5:++}) {
		
	}
```

**In autocomplete, "for" doesn't show up as a snippet, and "switch" does. But when using the switch snippet, it is using the contents of the "for" snippet.**

This could just be a syntax error, but I'm curious is anything else is wrong.

**Comment by YellowAfterlife** [comment]
Snippets are processed entirely by Ace, you can find examples [here](https://github.com/ajaxorg/ace/tree/master/lib/ace/snippets)

Indentation seems to be the issue with your snippets - they mix tabs and spaces and also there are no unindented lines between switch and for snippets - this works, for instance:
```
snippet switch
	switch ${1:var} {
		case ${2:1}:
			break;
			
		case ${3:2}:
			break;
			
		default:
			throw_error("Error! Reached default in switch statement");
	}

snippet for
	${1:_len} = array_length(_arr);
	for (${2:_i} = ${3:0}; ${4:$2 < _len}; $2${5:++}) {
		
	}
```

**Comment by brady-goldsworthy** [comment]
Tabs vs Spaces strikes back! That did the trick, thank you.
