### ISSUE TITLE
#import alias does not seem to work

### ISSUE THREAD

**Issue by Ced-Sharp** [YellowAfterlife/GMEdit#164]
I'm using GMEdit Beta v11.3.0.0 (version Dec 8, 2021) on Windows 11.
I'm using GameMaker Studio 2 with IDE v2.3.7.606 and runtime v2.3.7.476.

I created a new empty gml project with the following script:
```js
// script my_script.gml

#import display.get_gui_width as gui_width;
#import display.get_gui_height as gui_height;

var width = gui_width();
var height = gui_height();
```

Not only is intellisense not working (gui_width does not seem to exists) but the generated code in GameMaker Studio is invalid:
```js
#import display.get_gui_width /*#as gui_width*/;
#import display.get_gui_height /*#as gui_height*/;

var width = gui_width();
var height = gui_height();
```

Obviously the line starting with `#import` triggers an error.
Either I'm doing something wrong, and then please be lenient on this noob that I am, or the feature is not working.

**Comment by YellowAfterlife** [comment]
Using `in` instead of `as` may work. Pressing Ctrl+S a second time may also work if you've not used `#import` in the project before.

**Comment by Ced-Sharp** [comment]
Using either `as` or `in` produces different results, yet none work as expected.
![image](https://user-images.githubusercontent.com/56606410/147829708-5a67339c-4d48-4996-a010-9004f6ea7756.png)
