### ISSUE TITLE
Can't update YY

### ISSUE THREAD

**Issue by ogzozdemir** [YellowAfterlife/GMEdit#168]
Hello, I'm using GMEdit and loving it but I just ran into a problem. It seems that I can't save objects with asset type variable definition.

![1](https://user-images.githubusercontent.com/98316071/151863303-214f16e1-15fc-45b0-9a63-f6749b678e30.png)
![2](https://user-images.githubusercontent.com/98316071/151863308-07ff72cb-be26-45f9-a700-65485e125fcc.png)

Thank you.

**Comment by YellowAfterlife** [comment]
I'll need a sample YY file that causes the variable type to be printed as `asset<>`

**Comment by ogzozdemir** [comment]
Here you go, this is the object.
[oWerewolf.zip](https://github.com/YellowAfterlife/GMEdit/files/7977451/oWerewolf.zip)

**Comment by YellowAfterlife** [comment]
If you'd like a quick fix, check at least a single asset type on your `Asset` typed variables or change the lines in GMEdit to
```
sprite_attack:asset<sprite> = ...
```
I didn't realize that GM would let you use a variable with seemingly no valid choices for it.

**Comment by ogzozdemir** [comment]
Yeah that did the trick, thank you.
