### ISSUE TITLE
Warning when using constructor instances in variable_struct_* functions

### ISSUE THREAD

**Issue by Gabriel-Macena** [YellowAfterlife/GMEdit#169]
Not sure if this is a bug or intended behavior, but constructor instances cannot be cast to the base struct type, and will trigger a warning when used in any function that expects a struct.

![warn-constructor](https://user-images.githubusercontent.com/22627142/152700669-8a80ec2d-d0d6-489b-96ee-3e14535d342d.png)

**Comment by YellowAfterlife** [comment]
Fixed in 74748e9cc3db3db28c53cb9fac717b42232b7af7
