### ISSUE TITLE
Support for operator overloading / vector shorthand

### ISSUE THREAD

**Issue by ScottGrogin** [YellowAfterlife/GMEdit#170]
Would it be possible to add support for operator overloading or some sort of vector shorthand? I find that a lot of the code I write in GML around physics tends to be verbose because of the need to update x and y components separately. I know I could just make add, subtract, divide, and multiply functions, but it gets hard to read when doing many operations at a time and having to deal with nested functions. It would be nice to have the ability to use symbols ( +, -, *, /) instead.

**Comment by YellowAfterlife** [comment]
Doing this properly requires knowing types of every expression in the code and maintaining code structure on save-load, which is far more effort than what GMEdit currently does.

An alternative would be to write performance-critical code in [Haxe](https://haxe.org) in combination with my [Haxe➜GML target](https://github.com/YAL-Haxe/sfgml), which would allow to utilize Haxe's operator overloading and also inline functions as necessary.

**Comment by ScottGrogin** [comment]
Thanks for the alternative!
