### ISSUE TITLE
Global lookup seems no longer able to find individual global functions in script files in latest update

### ISSUE THREAD

**Issue by massim0g** [YellowAfterlife/GMEdit#172]
I often define multiple global functions within the same file, was previously able to jump to individual functions like the GMS2 global lookup but that no longer seems to be the case.
![image](https://user-images.githubusercontent.com/8515882/157973573-7fb12574-802b-4848-8b81-d136cf49cf7d.png)

**Comment by YellowAfterlife** [comment]
Fixed in the new version; you can also use Ctrl+G to navigate local symbols
