### ISSUE TITLE
Feature Request: Struct inner functions should be highlighted like a script 

### ISSUE THREAD

**Issue by FortressNebula** [YellowAfterlife/GMEdit#174]
If I had a struct like so:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/79470293/159177116-89ffcba3-a4c2-42f3-9cfa-f259e1e1614a.png">
then when I reference `Add` later on, the function would be highlighted like a normal variable.
<img width="212" alt="image" src="https://user-images.githubusercontent.com/79470293/159177251-e4e6548f-8089-4c53-8e18-1cc109902b3b.png">

My suggestion is for it to be highlighted like a script
<img width="213" alt="image" src="https://user-images.githubusercontent.com/79470293/159177336-3ed7da16-449f-4e17-ab3c-d4aa7b7bbfd9.png">

**Comment by YellowAfterlife** [comment]
This is same as #143 - GMEdit will highlight them accordingly if it's a local variable, but not for instance variables (due to `with`-loops potentially changing scope)
