### ISSUE TITLE
Possible broken setting

### ISSUE THREAD

**Issue by MangoDev1** [YellowAfterlife/GMEdit#175]
In `Preferences>Code Editor Settings`, there's a setting called `Animate scrolling`. Going by the name, I'm guessing it's supposed to toggle smooth scrolling, but it doesn't do anything when enabled or disabled. Is there just something I'm missing, or is it a broken setting from Ace?
![image](https://user-images.githubusercontent.com/94928669/163732415-dc057d11-1083-4f55-bc27-9c6a266146db.png)

**Comment by YellowAfterlife** [comment]
I took a closer look and the option isn't what it seems - it applied to "automated" scrolling, such as when you use Ctrl+G.

Electron/Chromium don't really have a built-in smooth scroll feature like Firefox does.
