### ISSUE TITLE
`instance_create_layer` now takes an additional parameter (GM 2.5)

### ISSUE THREAD

**Issue by giovanni-orciuolo** [YellowAfterlife/GMEdit#178]
In the latest version of GM (2.5 iirc), `instance_create_layer` takes an additional argument called `var_struct`. This is not reflected in GMEdit, which still considers it an error since it doesn't expect it.

**Comment by YellowAfterlife** [comment]
This is already fixed for next release in 35a02c11bf499efcff9322a292aeb240bdeb88b6
