### ISSUE TITLE
Allow disabling "is not part of" warnings

### ISSUE THREAD

**Issue by python-b5** [YellowAfterlife/GMEdit#179]
I have several objects that I create with `instance_create_layer` and assign variables to directly after, meaning that I get constant distracting warnings in the code within these objects that uses these variables.

Is is possible that a way to disable these warnings (while keeping all other ones) specifically?

**Comment by YellowAfterlife** [comment]
The warning tells you that the variable doesn't unconditionally exist on the object.

You could:
- Write `var inst = cast instance_create_layer(...);` to strip type information from the value.
- Assign those variables in object's Create.
- Add the variables to Variable Definitions.
- Add `/// @hint :varname` or `/// @hint {type} :varname` to object's Create event.
