### ISSUE TITLE
Time Source Constants do not exist

### ISSUE THREAD

**Issue by Dappermang** [YellowAfterlife/GMEdit#192]
These seem to be missing, as with several other newer 2.3 features in the last few months.
https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Time_Sources/Time_Sources.htm

**Comment by YellowAfterlife** [comment]
I fixed this some time ago but forgot about this report - the current version shows constants fine
![image](https://github.com/YellowAfterlife/GMEdit/assets/731492/0764959f-59fa-4035-85f7-08d957bac4f8)
