### ISSUE TITLE
Mac App Fails to Quit Completely on CMD+Q

### ISSUE THREAD

**Issue by NanoSharkGames** [YellowAfterlife/GMEdit#203]
There are two issues I came across when attempting to quit GMEdit on my Apple Silicon Mac:

1. When using Command+Q to attempt to quit, it fails to close the window & to quit the application
2. When I click the X button on the top right in the app, it closes the window but does not quit the application (EDIT 11/12/23: Electron apps are intended to remain active even after all windows are closed on Mac)

To quit the application, I have to either:

1. Right click the app's Dock icon & click the quit option
2. Force quit the app in Activity Monitor

Both of which take more time to quit, rather than the two ways in which it fails to quit.

I have attached a screen recording that demonstrates the issue.

https://github.com/YellowAfterlife/GMEdit/assets/40772036/0073b764-4390-4b4d-8e7f-3bdfbf08547b

**Comment by YellowAfterlife** [comment]
Allegedly the application is supposed to quit when using the menu (that's what Electron's sample code says, at least), but I no longer have a working Mac so it'll take some time before I'll be able to look into Mac-specific issues.

**Comment by NanoSharkGames** [comment]
After doing some digging online, I found a helpful article: https://memorytin.com/2018/04/24/electron-js-handle-cmdq-in-os-x/

It involves modifying the main.js file in the bin folder to support the CMD+Q shortcut in quitting the application. Hope that helps.
