### ISSUE TITLE
Allow adding variable number of Templates to type signature

### ISSUE THREAD

**Issue by KeeVeeGames** [YellowAfterlife/GMEdit#205]
For example, the built-in type `function` can have different sub-types such as `function<T>`, `function<T1, T2>`, `function<T2, T2, T3>` and so on. It is not possible to declare such behaviour in custom types neither with `@template` nor with `@hint`.

This can be done either similarly to `rest` type (but it may be hard to implement):
```js
/// @hint Function<Trest,T>:call(:Trest)->T
```
or as each individual declaration (like C# Func has):
```js
/// @hint Function<T>:call()->T
/// @hint Function<T1,T2>:call(:T1)->T2
/// @hint Function<T1,T2,T3>:call(:T1,:T2)->T3
/// @hint Function<T1,T2,T3,T4>:call(:T1,:T2,:T3)->T4
...
```
Which may be tedious but at least will work. For now it doesn't and only applies the last hint.

Ideally would be nice have it to work with callable types and #204

**Comment by YellowAfterlife** [comment]
Truth to be told, I have added [index_redirect](https://github.com/YellowAfterlife/GMEdit/wiki/JSDoc-tags#index_redirect) to avoid dealing with this specific issue for a time - overloads create a whole range of unexciting problems, and supporting "...rest" inside templates requires multiple packer/unpacker pseudo-types.

So it is far more tempting to add 8 macros hidden behind an `index_redirect` from GMEdit, and auto-generate separate type signatures for GMEdit.

**Comment by KeeVeeGames** [comment]
After I create an index redirected macros, should I use indexed versions of the function after? It's not like I can use the base one and it will understand the needed overload?

**Comment by YellowAfterlife** [comment]
This is now largely handled by [params_of](https://github.com/YellowAfterlife/GMEdit/wiki/Types#params_oft) / head_params_of.
