### ISSUE TITLE
Linter shows warns for local (i.e. 'var') constructor sub-methods that are inside non-constructor methods saying "function is not a constructor" despite the sub-method being a constructor

### ISSUE THREAD

**Issue by MorphoMonarchy** [YellowAfterlife/GMEdit#209]
The title might be a bit confusing but hopefully the code below will make more sense. When I declare a constructor method inside of a non-constructor method as a local variable (i.e. 'var' ) it causes a warning message/highlight to be displayed. It's not a big deal, but figured it might be worth noting in case others are running into this issue. Also, in case you're wondering, the code design is based on [JuJuAdam's GitHub post on 'Fluent Design'](https://github.com/JujuAdams/ThoughtsOnGameMaker/blob/main/technique-5-fluent.md). Thanks!

Edit: I tested for static and global keywords, as well as testing inside of global constructors (outside of standard GameMaker objects) and it looks like this issue only occurs if the method is declared as a local 'var'.

Screenshot:
![image](https://github.com/YellowAfterlife/GMEdit/assets/51758249/46f2c2db-a207-47df-b402-bd0c77071dc0)

Code:`
      
    //Components
    buildComponents = function(_instanceID){
      var _inner = function(_entID) constructor { //<---Even though this is a valid constructor, a warn is still displayed as if it is not
          
          __entID = _entID;
          
          playerController = function(_player_controller:obj_con_player){
              __entID.addComponent(ENT_COMP_KEY_PLAYER_CON, obj_con_player);
              return self;
          }
          
          animated = function(){
              __entID.addComponent(ENT_COMP_KEY_ANIMATED, true);
              return self;
          }
      }
  
      return new _inner(_instanceID); //<---Warn is displayed here
     }
`

**Comment by YellowAfterlife** [comment]
GMEdit cannot currently distinguish between a regular expression-function and an constructor expression-function - the function type is already a special case, so introducing another one is a little complex. I'll get to it later on

**Comment by MorphoMonarchy** [comment]
Good to know! Yeah, like I said it's not a big deal since it doesn't actually impact compilation or anything, but figured I'd mention it for those who get stressed out from having a warn on their code lol.
