### ISSUE TITLE
Saving files in GMEdit shows fake duplicated objects in asset browser

### ISSUE THREAD

**Issue by DF1229** [YellowAfterlife/GMEdit#214]
Hi there, I just started using GM and found GMEdit, super happy with the improvements on the built-in code editor!
I found one small issue however, which I think might be related to GMEdit, but it also might just be a skill issue on my part.

After opening my project in both GM and GMEdit, I went to edit the code for events. All good so far.
However, when I return to GM and reload the files (or have it done automatically), I find that the object(s) I modified are now listed multiple times in the asset browser...
I checked myself, and the files are only actually there one time, and after closing and re-opening the project in GM the duplicate objects are gone. So it only looks like they exist multiple times, I can even open all of them in the workspace.

This doesn't happen with other external IDE's, so my current theory is that it either has to do with the way GMEdit saves the files to disk, or the way GM reloads the files.
I couldn't find the code responsible for saving files in this repo, and I couldn't find a good spot to post about this on the GMC forums, so here I am.

Short video as demonstration:
https://github.com/YellowAfterlife/GMEdit/assets/9870580/7d20f4f0-5b1e-4dea-a535-c7393fa14c9b

For context, I'm on Windows 11 Pro 23H2, GM IDE v2024.2.0.132 and downloaded GMEdit off itch.io earlier today.

**Comment by YellowAfterlife** [comment]
There are other external IDEs..? Unless you mean the Stitch VS Code extension

Not too much to do with GMEdit - try opening your object YY in a text/code editor, make any change (add a linebreak at the end, add a space somewhere), save, and the GM IDE will duplicate it in the resource tree.

**Comment by DF1229** [comment]
Weirdly interesting, might dig deeper into this later to see if I can find out what's causing this...
I did indeed mean vscode, but I wasn't aware of the Stitch extension, cool to see different parts of the community make their own tools!
