### ISSUE TITLE
Unable to open GML dialects directory on Windows ("/" instead of "\")

### ISSUE THREAD

**Issue by desvaters** [YellowAfterlife/GMEdit#215]
When trying to open the GML dialects directory from within GMEdit, I get a file not found error.
I assume that the problem is that forward slashes are inserted after "Roaming\" instead of backward slashes.

(Version: "GMEdit-Beta-Windows" from Mar 5, 2024)

![grafik](https://github.com/YellowAfterlife/GMEdit/assets/71886240/3b38f589-53c3-4cf3-b48a-0a8b01b5ce43)

**Comment by desvaters** [comment]
I think, something like
`var pathSeparator = Sys.systemName() == "Windows" ? "\\" : "/";`
could work to use the right path separator, but that should be changed all over the code, right?

**Comment by YellowAfterlife** [comment]
That's quite funny, just recently a similar bug was fixed in [another function](https://github.com/electron/electron/issues/11617) after I reported it 6 years ago.
