### ISSUE TITLE
Macros unusable in int-type Variable Definitions

### ISSUE THREAD

**Issue by Galbenshire** [YellowAfterlife/GMEdit#222]
For objects, if you try to set an int-type variable in Variable Definitions to a macro, you are unable to save _any_ changes made to that object.
If you try to, GMEdit will throw an error saying the macro is not the right type.
This is despite GameMaker itself being perfectly fine with you using a macro in this context.
![GMEditError](https://github.com/user-attachments/assets/257684f4-3403-4575-9887-497f260ed69e)
It is worth noting that if the variable is of type real, this error does not occur.
![GMEditError2](https://github.com/user-attachments/assets/80df7017-d13c-4adc-9ecf-1418fafd4cad)

**Comment by YellowAfterlife** [comment]
I'll get to this - initially, variable definition types meant that GM (and GMEdit) would make sure that the expression is a matching type, but now almost all of them are equivalent to Expression.
