### ISSUE TITLE
Creating Events via GMEdit results in a build fail in 2024.8

### ISSUE THREAD

**Issue by Ryemanni** [YellowAfterlife/GMEdit#223]
Hello, in gm version 2024.8 if you create new events via GMEdit and not through the IDE, the new events result in a failed build accompanied by the "Cannot load this new project because it, or its linked prefab libraries, need upgrading."

I managed to track down the problem to the .yy file of the object. In the "eventList" array, if an event is created through the IDE it shows:
`{"$GMEvent":"v1","%Name":"","collisionObjectId":null,"eventNum":0,"eventType":3,"isDnD":false,"name":"","resourceType":"GMEvent","resourceVersion":"2.0",}`
and via GMEDIT:
`{"$GMEvent":"","%Name":"","collisionObjectId":null,"eventNum":0,"eventType":3,"isDnD":false,"name":"","resourceType":"GMEvent","resourceVersion":"2.0",}`

As you can see, the "v1" is missing in the event created with GMEdit. If I manually add in the "v1" the project builds normally.

This happens consistently in gm 2024.8 with runtime v2024.8.0216, but I can't say for earlier versions as I skipped them and went straight from 2023.11 to 2024.8.
Thank you!

**Comment by cauehenrique** [comment]
Same here, was searching if someone found a workaround for this issue...

**Comment by YellowAfterlife** [comment]
You can try building the latest git version from source code, but more generally 2024.6 and onward became extremely strict towards the YY format - even incorrect field order (as seen here) is now considered a grave mistake and will result in build failure.

I do not know what result these changes pursue.

**Comment by YellowAfterlife** [comment]
This specific issue should be resolved in the latest release

**Comment by cauehenrique** [comment]
Thank you! Keep up the great work, been using GMEdit on my full-time job and it works flawlessly.
