### ISSUE TITLE
Support for Love2D / PyGame

### ISSUE THREAD

**Issue by IntinteDAO** [YellowAfterlife/GMEdit#229]
Just an idea. I thought it might be cool to be able to write code in other languages like PyGame or Love2D, which are also for game development, but don't have cool editors. Of course, this type of solution would make it easier to write in these engines in my opinion, where some things could be clickable.

**Comment by YellowAfterlife** [comment]
The reason GMEdit is (relatively) good at its job is that it's specialized - everything in the program is modeled based on how GameMaker works and how people typically use GameMaker. Without that I'd be making a VS Code replica.

That said, if you have a lot of free time on your hands, you _can_ add support for additional languages as plugins (e.g. there's an example for INI included), but it's far easier to use existing tools.
