### ISSUE TITLE
"GML dialects directory" Link Fails

### ISSUE THREAD

**Issue by gudenau** [YellowAfterlife/GMEdit#64]
When clicking the "GML dialects directory" link in Preferences it does not open the directory, but instead dumps the "xdg-open" help to console.

Output:
```
xdg-open -- opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
```

**Comment by YellowAfterlife** [comment]
Well,

I don't know.
You can do
```js
console.log(electron_FileWrap.userPath + "/api")
Electron_Shell.openExternal(electron_FileWrap.userPath + "/api")
```
and this logs
```js
/home/<user>/.config/AceGM/GMEdit/api
```
which is the correct path for xdg-open,
and calls [openExternal](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options),
which [calls XdgOpen](https://github.com/electron/electron/blob/b6246dcf122e584c672566877cb60d33dbc4705e/shell/common/platform_util_linux.cc#L82)
which [calls really just runs xdg-open](https://github.com/electron/electron/blob/b6246dcf122e584c672566877cb60d33dbc4705e/shell/common/platform_util_linux.cc#L47), and how does the path get lost.

See about running GMEdit on a dev version of Electron / filing a bug with them.

**Comment by Zephia-Sero** [comment]
I was having this issue too, it seems (from my limited and terrifying testing of symlinking node, npm, and sh to the project directory, making an executable shell script named `xdg-open` which prints the args passed to it, and running the program with `PATH=. npm start`) that `Shell.openExternal` does not give `xdg-open` **any** args and silently fails if there is no protocol preceding the URI.

**Comment by YellowAfterlife** [comment]
If you can test this on current Electron and file a bug, it might get fixed eventually - my other [Shell API bug](https://github.com/electron/electron/issues/11617) has turned 5 this year.

**Comment by Zephia-Sero** [comment]
Actually, I think it might be intentional, since there also exists `Shell.openPath`, which seems to work fine without having to prefix it with the protocol `file://`.
